<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>KlrpxyGameplayTags.Runtime</AssemblyName>
    <RootNamespace>Klrpxy.Gameplay.Tags.Runtime</RootNamespace>
    <LangVersion>8.0</LangVersion>
    <AssemblyVersion>0.2.0.0</AssemblyVersion>
    <Nullable>disable</Nullable>
  </PropertyGroup>
</Project>
