using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Klrpxy.Gameplay.Stats.Generator
{
    [Generator]
    public sealed class GameplayStatsGenerator : ISourceGenerator
    {
        private const string StatSetTypeName = "Klrpxy.Gameplay.Stats.StatSet";
        private const string RangeStatTypeName = "Klrpxy.Gameplay.Stats.RangeStat";
        private const string ResourceTypeName = "Klrpxy.Gameplay.Stats.Resource";
        private const string StatTypeName = "Klrpxy.Gameplay.Stats.Stat";

        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new StatSetReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            var receiver = (StatSetReceiver)context.SyntaxReceiver;
            var generatedStatSets = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
            foreach (ClassDeclarationSyntax declaration in receiver.Candidates)
            {
                SemanticModel semanticModel = context.Compilation.GetSemanticModel(declaration.SyntaxTree);
                var symbol = semanticModel.GetDeclaredSymbol(declaration) as INamedTypeSymbol;
                if (!IsSupportedStatSet(declaration, symbol) || !generatedStatSets.Add(symbol))
                {
                    continue;
                }

                IPropertySymbol[] members = symbol.GetMembers()
                    .OfType<IPropertySymbol>()
                    .Where(member => GetMemberKind(member).HasValue)
                    .ToArray();
                if (members.Length == 0)
                {
                    continue;
                }

                context.AddSource(
                    GetHintName(generatedStatSets.Count),
                    SourceText.From(GenerateStatSet(context.Compilation.AssemblyName, symbol, members), Encoding.UTF8));
            }
        }

        private static bool IsSupportedStatSet(
            ClassDeclarationSyntax declaration,
            INamedTypeSymbol symbol)
        {
            if (symbol == null
                || declaration.TypeParameterList != null
                || !declaration.Modifiers.Any(modifier => modifier.IsKind(SyntaxKind.PartialKeyword))
                || (!(declaration.Parent is CompilationUnitSyntax)
                    && !(declaration.Parent is NamespaceDeclarationSyntax)))
            {
                return false;
            }

            for (INamedTypeSymbol current = symbol.BaseType; current != null; current = current.BaseType)
            {
                if (string.Equals(current.ToDisplayString(), StatSetTypeName, StringComparison.Ordinal))
                {
                    return true;
                }
            }

            return false;
        }

        private static MemberKind? GetMemberKind(IPropertySymbol property)
        {
            if (property.DeclaredAccessibility != Accessibility.Public
                || property.IsStatic
                || property.GetMethod == null
                || property.SetMethod != null)
            {
                return null;
            }

            string typeName = property.Type.ToDisplayString();
            if (string.Equals(typeName, StatTypeName, StringComparison.Ordinal))
            {
                return MemberKind.Stat;
            }

            if (string.Equals(typeName, RangeStatTypeName, StringComparison.Ordinal))
            {
                return MemberKind.RangeStat;
            }

            return string.Equals(typeName, ResourceTypeName, StringComparison.Ordinal)
                ? MemberKind.Resource
                : (MemberKind?)null;
        }

        private static string GenerateStatSet(
            string assemblyName,
            INamedTypeSymbol statSet,
            IReadOnlyList<IPropertySymbol> members)
        {
            string namespaceName = statSet.ContainingNamespace.IsGlobalNamespace
                ? string.Empty
                : statSet.ContainingNamespace.ToDisplayString();
            string accessibility = statSet.DeclaredAccessibility == Accessibility.Public
                ? "public"
                : "internal";
            var source = new StringBuilder();
            source.AppendLine("// <auto-generated />");

            if (namespaceName.Length > 0)
            {
                source.Append("namespace ").Append(namespaceName).AppendLine();
                source.AppendLine("{");
            }

            string indent = namespaceName.Length > 0 ? "    " : string.Empty;
            source.Append(indent).Append(accessibility).Append(" partial class ")
                .Append(EscapeIdentifier(statSet.Name)).AppendLine();
            source.Append(indent).AppendLine("{");

            foreach (IPropertySymbol stat in members.Where(member => GetMemberKind(member) == MemberKind.Stat))
            {
                string path = assemblyName + "::" + statSet.ToDisplayString() + "." + stat.Name;
                string statType = stat.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                source.Append(indent).Append("    public static readonly global::Klrpxy.Gameplay.Stats.StatKey<")
                    .Append(statType).Append("> ")
                    .Append(stat.Name).AppendLine("Key =");
                source.Append(indent).Append("        CreateKey<").Append(statType).Append(">(typeof(")
                    .Append(statSet.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).Append(") , \"")
                    .Append(path).Append("\", set => ((")
                    .Append(statSet.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).Append(")set).")
                    .Append(EscapeIdentifier(stat.Name)).AppendLine(");");
            }

            source.AppendLine();
            source.Append(indent).AppendLine("    private static readonly global::Klrpxy.Gameplay.Stats.StatMemberDescriptor[] __GeneratedMembers =");
            source.Append(indent).AppendLine("    {");
            foreach (IPropertySymbol member in members)
            {
                string path = assemblyName + "::" + statSet.ToDisplayString() + "." + member.Name;
                string memberType = member.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                source.Append(indent).Append("        CreateMember<").Append(memberType).Append(">(\"")
                    .Append(path).Append("\", global::Klrpxy.Gameplay.Stats.StatMemberKind.")
                    .Append(GetMemberKind(member).Value).Append(", set => ((")
                    .Append(statSet.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).Append(")set).")
                    .Append(EscapeIdentifier(member.Name)).AppendLine("),");
            }

            source.Append(indent).AppendLine("    };");
            source.AppendLine();
            source.Append(indent).AppendLine("    protected override void AppendGeneratedMembers(global::System.Collections.Generic.ICollection<global::Klrpxy.Gameplay.Stats.StatMemberDescriptor> members)");
            source.Append(indent).AppendLine("    {");
            source.Append(indent).AppendLine("        base.AppendGeneratedMembers(members);");
            source.Append(indent).AppendLine("        foreach (global::Klrpxy.Gameplay.Stats.StatMemberDescriptor member in __GeneratedMembers)");
            source.Append(indent).AppendLine("        {");
            source.Append(indent).AppendLine("            members.Add(member);");
            source.Append(indent).AppendLine("        }");
            source.Append(indent).AppendLine("    }");

            source.Append(indent).AppendLine("}");
            if (namespaceName.Length > 0)
            {
                source.AppendLine("}");
            }

            return source.ToString();
        }

        private static string EscapeIdentifier(string identifier)
        {
            return SyntaxFacts.GetKeywordKind(identifier) == SyntaxKind.None
                ? identifier
                : "@" + identifier;
        }

        private static string GetHintName(int generatedStatSetCount)
        {
            return "KlrpxyGameplayStats." + generatedStatSetCount + ".g.cs";
        }

        private sealed class StatSetReceiver : ISyntaxReceiver
        {
            public List<ClassDeclarationSyntax> Candidates { get; } = new List<ClassDeclarationSyntax>();

            public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
            {
                var declaration = syntaxNode as ClassDeclarationSyntax;
                if (declaration != null)
                {
                    Candidates.Add(declaration);
                }
            }
        }

        private enum MemberKind
        {
            Stat,
            RangeStat,
            Resource
        }
    }
}
