<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>KlrpxyGameplayStats</AssemblyName>
    <RootNamespace>Klrpxy.Gameplay.Stats.Generator</RootNamespace>
    <LangVersion>8.0</LangVersion>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.8.0" PrivateAssets="all" />
    <AdditionalFiles Include="AnalyzerReleases.Unshipped.md" />
    <Compile Remove="unity-package/**/*.cs" />
  </ItemGroup>
</Project>
