using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Klrpxy.Gameplay.Tags.Generator
{
    [Generator]
    public sealed class GameplayTagsGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new RootReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            context.AddSource("GenerateGameplayTagsAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8));

            RootReceiver receiver = context.SyntaxReceiver as RootReceiver;
            ClassDeclarationSyntax root = receiver == null
                ? null
                : receiver.Roots.FirstOrDefault(candidate =>
                    IsValidRoot(candidate) && HasOfficialMarker(context.Compilation, candidate));
            AdditionalText table = context.AdditionalFiles.SingleOrDefault(
                file => string.Equals(
                    Path.GetFileName(file.Path),
                    "GameplayTags.KlrpxyGameplayTags.additionalfile",
                    StringComparison.Ordinal));

            if (root == null || table == null)
            {
                return;
            }

            SourceText tableText = table.GetText(context.CancellationToken);
            if (tableText == null)
            {
                return;
            }

            context.AddSource(
                "GameplayTags.g.cs",
                SourceText.From(GenerateHierarchy(root, ParsePaths(tableText)), Encoding.UTF8));
        }

        private const string AttributeSource = @"// <auto-generated />
namespace Klrpxy.Gameplay.Tags
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public sealed class GenerateGameplayTagsAttribute : global::System.Attribute
    {
    }
}
";

        private static bool IsValidRoot(ClassDeclarationSyntax root)
        {
            return root.Modifiers.Any(SyntaxKind.StaticKeyword)
                && root.Modifiers.Any(SyntaxKind.PartialKeyword);
        }

        private static bool HasOfficialMarker(
            Compilation compilation,
            ClassDeclarationSyntax root)
        {
            SemanticModel semanticModel = compilation.GetSemanticModel(root.SyntaxTree);
            foreach (AttributeSyntax attribute in root.AttributeLists.SelectMany(list => list.Attributes))
            {
                IMethodSymbol constructor = semanticModel.GetSymbolInfo(attribute).Symbol as IMethodSymbol;
                if (constructor != null)
                {
                    if (IsOfficialMarkerType(constructor.ContainingType.ToDisplayString()))
                    {
                        return true;
                    }

                    continue;
                }

                IdentifierNameSyntax identifier = attribute.Name as IdentifierNameSyntax;
                IAliasSymbol alias = identifier == null ? null : semanticModel.GetAliasInfo(identifier);
                if (alias != null)
                {
                    if (IsOfficialMarkerType(alias.Target.ToDisplayString()))
                    {
                        return true;
                    }

                    continue;
                }

                bool? syntaxAliasIsOfficial = identifier == null
                    ? (bool?)null
                    : IsOfficialMarkerAlias(root, identifier.Identifier.ValueText);
                if (syntaxAliasIsOfficial.HasValue)
                {
                    if (syntaxAliasIsOfficial.Value)
                    {
                        return true;
                    }

                    continue;
                }

                if (IsMarkerName(attribute.Name.ToString()))
                {
                    return true;
                }
            }

            return false;
        }

        private static bool? IsOfficialMarkerAlias(ClassDeclarationSyntax root, string aliasName)
        {
            foreach (SyntaxNode scope in root.Ancestors())
            {
                IEnumerable<UsingDirectiveSyntax> usings;
                NamespaceDeclarationSyntax namespaceDeclaration = scope as NamespaceDeclarationSyntax;
                CompilationUnitSyntax compilationUnit = scope as CompilationUnitSyntax;
                if (namespaceDeclaration != null)
                {
                    usings = namespaceDeclaration.Usings;
                }
                else if (compilationUnit != null)
                {
                    usings = compilationUnit.Usings;
                }
                else
                {
                    continue;
                }

                UsingDirectiveSyntax match = usings.FirstOrDefault(usingDirective =>
                    usingDirective.Alias != null
                    && string.Equals(
                        usingDirective.Alias.Name.Identifier.ValueText,
                        aliasName,
                        StringComparison.Ordinal));
                if (match != null)
                {
                    return IsOfficialMarkerType(NormalizeName(match.Name.ToString()));
                }
            }

            return null;
        }

        private static bool IsMarkerName(string name)
        {
            name = NormalizeName(name);

            return string.Equals(name, "GenerateGameplayTags", StringComparison.Ordinal)
                || string.Equals(name, "GenerateGameplayTagsAttribute", StringComparison.Ordinal)
                || string.Equals(name, "Klrpxy.Gameplay.Tags.GenerateGameplayTags", StringComparison.Ordinal)
                || IsOfficialMarkerType(name);
        }

        private static string NormalizeName(string name)
        {
            const string globalPrefix = "global::";
            return name.StartsWith(globalPrefix, StringComparison.Ordinal)
                ? name.Substring(globalPrefix.Length)
                : name;
        }

        private static bool IsOfficialMarkerType(string name)
        {
            return string.Equals(
                name,
                "Klrpxy.Gameplay.Tags.GenerateGameplayTagsAttribute",
                StringComparison.Ordinal);
        }

        private static IReadOnlyList<string[]> ParsePaths(SourceText text)
        {
            var paths = new List<string[]>();
            var seen = new HashSet<string>(StringComparer.Ordinal);

            foreach (TextLine line in text.Lines)
            {
                string value = line.ToString().Trim();
                if (value.Length == 0)
                {
                    continue;
                }

                string[] segments = value.Split('.');
                for (int length = 1; length <= segments.Length; length++)
                {
                    string path = string.Join(".", segments, 0, length);
                    if (seen.Add(path))
                    {
                        paths.Add(segments.Take(length).ToArray());
                    }
                }
            }

            return paths;
        }

        private static string GenerateHierarchy(ClassDeclarationSyntax root, IReadOnlyList<string[]> paths)
        {
            string namespaceName = GetNamespace(root);
            string accessibility = root.Modifiers.Any(SyntaxKind.PublicKeyword) ? "public" : "internal";
            var source = new StringBuilder();

            source.AppendLine("// <auto-generated />");
            if (namespaceName.Length > 0)
            {
                source.Append("namespace ").Append(namespaceName).AppendLine();
                source.AppendLine("{");
            }

            string indent = namespaceName.Length > 0 ? "    " : string.Empty;
            source.Append(indent).Append(accessibility).Append(" static partial class ")
                .Append(root.Identifier.ValueText).AppendLine();
            source.Append(indent).AppendLine("{");
            foreach (string[] path in paths.Where(path => path.Length == 1))
            {
                source.Append(indent).Append("    public static Tag.").Append(GetNodeName(path))
                    .Append(' ').Append(path[0]).Append(" => Tag.").Append(GetNodeName(path))
                    .AppendLine(".Instance;");
            }

            source.Append(indent).AppendLine("}");
            source.AppendLine();
            source.Append(indent).AppendLine("public class Tag");
            source.Append(indent).AppendLine("{");
            source.Append(indent).AppendLine("    private readonly string path;");
            source.Append(indent).AppendLine("    private readonly Tag parent;");
            source.AppendLine();
            source.Append(indent).AppendLine("    private Tag(string path, Tag parent)");
            source.Append(indent).AppendLine("    {");
            source.Append(indent).AppendLine("        this.path = path;");
            source.Append(indent).AppendLine("        this.parent = parent;");
            source.Append(indent).AppendLine("    }");
            source.AppendLine();
            source.Append(indent).AppendLine("    public string GetPath() => path;");
            source.AppendLine();
            source.Append(indent).AppendLine("    public Tag GetParent() => parent;");

            foreach (string[] path in paths)
            {
                AppendNode(source, indent, path, paths);
            }

            source.Append(indent).AppendLine("}");
            if (namespaceName.Length > 0)
            {
                source.AppendLine("}");
            }

            return source.ToString();
        }

        private static void AppendNode(
            StringBuilder source,
            string indent,
            string[] path,
            IReadOnlyList<string[]> paths)
        {
            string nodeName = GetNodeName(path);
            string fullPath = string.Join(".", path);
            string parent = path.Length == 1
                ? "null"
                : GetNodeName(path.Take(path.Length - 1).ToArray()) + ".Instance";

            source.AppendLine();
            source.Append(indent).Append("    public sealed class ").Append(nodeName).AppendLine(" : Tag");
            source.Append(indent).AppendLine("    {");
            source.Append(indent).Append("        private ").Append(nodeName).Append("() : base(\"")
                .Append(fullPath).Append("\", ").Append(parent).AppendLine(")");
            source.Append(indent).AppendLine("        {");
            source.Append(indent).AppendLine("        }");
            source.AppendLine();
            source.Append(indent).Append("        public static ").Append(nodeName)
                .Append(" Instance { get; } = new ").Append(nodeName).AppendLine("();");

            foreach (string[] child in paths.Where(candidate =>
                candidate.Length == path.Length + 1 && HasPrefix(candidate, path)))
            {
                source.AppendLine();
                source.Append(indent).Append("        public ").Append(GetNodeName(child)).Append(' ')
                    .Append(child[child.Length - 1]).Append(" => ").Append(GetNodeName(child))
                    .AppendLine(".Instance;");
            }

            source.Append(indent).AppendLine("    }");
        }

        private static bool HasPrefix(string[] candidate, string[] prefix)
        {
            for (int index = 0; index < prefix.Length; index++)
            {
                if (!string.Equals(candidate[index], prefix[index], StringComparison.Ordinal))
                {
                    return false;
                }
            }

            return true;
        }

        private static string GetNodeName(string[] path)
        {
            return "__" + string.Join("_", path) + "Node";
        }

        private static string GetNamespace(SyntaxNode node)
        {
            return string.Join(".", node.Ancestors()
                .OfType<NamespaceDeclarationSyntax>()
                .Reverse()
                .Select(declaration => declaration.Name.ToString()));
        }

        private sealed class RootReceiver : ISyntaxReceiver
        {
            public List<ClassDeclarationSyntax> Roots { get; } = new List<ClassDeclarationSyntax>();

            public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
            {
                ClassDeclarationSyntax declaration = syntaxNode as ClassDeclarationSyntax;
                if (declaration == null || declaration.AttributeLists.Count == 0)
                {
                    return;
                }

                Roots.Add(declaration);
            }
        }
    }
}
